# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows/"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "docker"
    directory: "/.docker/"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "bun"
    directory: "/html/"
    schedule:
      interval: "weekly"
      day: "saturday"
