# The workflow to publish the package
name: "Publish"

# Controls when the workflow will run
on:
  release:
    types: [ created ]

jobs:
  publish:
    # Run on the latest Ubuntu
    runs-on: ubuntu-latest

    # Required for tokenless (OIDC)
    permissions:
      id-token: write
      contents: read

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Set up Bun"
        uses: oven-sh/setup-bun@v2

      - name: "Install dependencies"
        working-directory: html
        run: bun install

      - name: "Build project"
        working-directory: html
        run: bun run build

      - name: "Set up Node.js"
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - name: "Publish the package to npm"
        working-directory: html/dist
        run: npm publish --access public --provenance
